### ISSUE TITLE
why are management services detached from the central server?

### ISSUE THREAD

**Issue by AnttiLuoma** [ria-ee/X-Road#11]
_From @eramirez-sv on February 26, 2017 22:31_

I have noticed that registering a new security server goes straight to the central server  while registration of new subsystem get routed to the appointed management services provider. 
I have gone though the documentation and I understand the current architecture, but I am still not clear  why it is broken up that way. The security server appointed to provide management services needs to service  all other security servers, why isn't this a function within the central server, wouldn't that be more efficient/cost effective? 
I am sure there's a perfectly reasonable explanation, I'm just trying to figure out what it is.
thanks!

_Copied from original issue: vrk-kpa/xroad-public#34_

**Comment by VitaliStupin** [comment]
According to doc/Protocols/pr-mserv_x-road_protocol_for_management_services_1.9_Y-883-29-1.docx
2.3	authCertReg – Security Server Authentication Certificate Registration:

Unlike the other requests, the authentication certificate registration request cannot be sent as a regular X-Road request. This is caused by a bootstrapping problem – sending an X Road message requires that the authentication certificate of the security server is registered at the central server. However, the certificate is registered only as a result of invoking this service. Therefore, another mechanism is needed.
The authentication certificate registration request is sent to the central server directly via HTTPS. When making the HTTPS connection the client MUST verify that the server uses the TLS certificate that is given in the global configuration.

**Comment by eramirez-sv** [comment]
that makes sense, thanks for the explanation.
Best,
