### ISSUE TITLE
upgrade installation and roadmap

### ISSUE THREAD

**Issue by eramirez-sv** [ria-ee/X-Road#29]
We are currently running version 6.7 and I would like to upgrade our installation, a few questions:

1- What's the recommended procedure for upgrading: back up current config, wipe out the server, do a clean install and restore previous config?
2- Can I upgrade only security servers or do I need to upgrade the Central Server as well?
3- It will be best to do this only for major releases, Is there a project roadmap/schedule?

Thanks!

**Comment by iluwatar** [comment]
1) It is recommended to create configuration backup before upgrading. The packages are upgraded with normal `apt-get update` and `apt-get upgrade`. Note that the central servers need to be upgraded first and when upgrading to version equal or greater than 6.9x you are going to need to set Certificate Profile Info for Certification Services. We use value of `ee.ria.xroad.common.certificateprofile.impl.FiVRKCertificateProfileInfoProvider`.

2) In general it is recommended to upgrade both central servers and security servers and for 6.9x you must do this since it introduces global configuration versioning.

3) It is probably good idea to follow roughly the update schedule of the X-Road partners Estonia and Finland. In Finland the previous production version was 6.7.13 and currently we are upgrading to 6.9x. There is business roadmap publicly available at https://github.com/vrk-kpa/xroad-joint-development/blob/master/ROADMAP.md but it does not contain version upgrade schedules.

**Comment by eramirez-sv** [comment]
Thanks iluwatar, I am compiling our own version for our country (SV), I will test upgrading using dpkg. In our current version (6.7.13) I had create a ee.ria.xroad.common.util.SVSubjectClientIdDecoder class. For the current version 6.9, I should do ee.ria.xroad.common.certificateprofile.impl.SVCertificateProfileInfoProvider ?

Also, the source code in src/package/debian only has a folders for trusty and lucid. Is there support for ubuntu 16/Xenial?.

**Comment by iluwatar** [comment]
Yes, for versions 6.8x and greater you are going to need the customized certificate profile info provider. There is no Ubuntu 16 support and it has been agreed that the next supported version will be Ubuntu 18 (it is on the roadmap).
